language: android
jdk: oraclejdk8
sudo: required
dist: precise # For 7.5GB of memory since the emulator requires a big chunk.
env:
  matrix:
    - ANDROID_TARGET=android-27
  global:
    - ADB_INSTALL_TIMEOUT=12
android:
  components:
    - tools
    - platform-tools
    # The BuildTools version used
    - build-tools-27.0.3
    # The SDK version used to compile the project
    - android-27
    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
  # Begin spinning up an emulator in the background
  - make emulator

script:
  - make quality
  - make test
  # Check if emulator has finished booting
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - travis_wait make e2e
  # Script to print lint information in logs.
  - ./gradlew connectedAndroidTest